version: '3.7'
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - flownetwork

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9100:9000"
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./clickhouse_init.sql:/docker-entrypoint-initdb.d/clickhouse_init.sql
      - ./clickhouse_init.sh:/docker-entrypoint-initdb.d/clickhouse_init.sh
      - ./clickhouse_user_init.sh:/docker-entrypoint-initdb.d/clickhouse_user_init.sh
    networks:
      - flownetwork   

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    depends_on:
      - clickhouse
    networks:
      - flownetwork


  ipfix-generator:
    image: ghcr.io/jfwenisch/ipfix-generator:latest
    container_name: ipfix-generator
    ports:
      - "8080:8080"
    networks:
      - flownetwork
    restart: unless-stopped


  ipfixcol2:
    image: ipfixcol2:latest
    container_name: ipfixcol2
    ports:
      - "4739:4739"
      - "9995:9995"
    
    depends_on:
      - kafka
      - clickhouse
    networks:
      - flownetwork

volumes:
  kafka_data:
networks:
  flownetwork:
    driver: bridge
